version: 1.0.{build}

image: Visual Studio 2017

clone_folder: c:\projects\zabbix
shallow_clone: true

matrix:
    fast_finish: false

platform:
    - x64

configuration:
    - Release

environment:
    matrix:
      - PLATFORM: x64
        BUILDER: CMake
        GENERATOR: "NMake Makefiles"
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#      - PLATFORM: x86
#        BUILDER: CMake
#        GENERATOR: "NMake Makefiles"
#        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

init:
  - git config --global core.autocrlf input
  - ps: 'Write-Host "Building Zabbix branch: $env:APPVEYOR_REPO_BRANCH" -ForegroundColor Magenta'
  #- ps: |
  #  Write-Host "Build worker environment variables:" -ForegroundColor Magenta
  #      Get-ChildItem Env: | %{"{0}={1}" -f $_.Name,$_.Value}
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" if "%GENERATOR%"=="NMake Makefiles" if "%PLATFORM%"=="x86" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" if "%GENERATOR%"=="NMake Makefiles" if "%PLATFORM%"=="x64" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" if "%GENERATOR%"=="NMake Makefiles" if "%PLATFORM%"=="x86" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" if "%GENERATOR%"=="NMake Makefiles" if "%PLATFORM%"=="x64" call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" if "%GENERATOR%"=="NMake Makefiles" if "%PLATFORM%"=="x64" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

install:
    - set ZBX_VER=3.4.16
    - set PCRE_VER=8.43
    - mkdir C:\projects\deps
    - mkdir C:\projects\deps\libs
    - cd C:\projects\deps
    - appveyor DownloadFile https://ftp.pcre.org/pub/pcre/pcre-%PCRE_VER%.zip -FileName pcre.zip
    - 7z e -y pcre.zip -oC:\projects\deps\pcre
    - mkdir C:\projects\deps\libs\pcre

build_script:
    - echo %configuration%
    - cd C:\projects\deps\pcre
    - mkdir build
    - cd build
    - cmake -G "NMake Makefiles"
      "-DCMAKE_BUILD_TYPE=%configuration%"
      "-DCMAKE_INSTALL_PREFIX=C:\projects\deps\libs\pcre"
      "-DPCRE_BUILD_PCRECPP=OFF"
      "-DPCRE_SUPPORT_UNICODE_PROPERTIES=ON"
      "-DPCRE_SUPPORT_UTF=ON"
      "-DCMAKE_C_FLAGS_RELEASE:string="/MT"" ..
    - nmake install
    - cd C:\projects\zabbix
    - cd build\win32\project
    - copy ..\include\config.h ..\..\..\include\ >nul 2>&1
    - nmake CPU=AMD64 TLS=openssl TLSINCDIR="C:\OpenSSL-v111-Win64\include" TLSLIBDIR="C:\OpenSSL-v111-Win64\lib" PCREINCDIR="C:\projects\deps\libs\pcre\include" PCRELIBDIR="C:\projects\deps\libs\pcre\lib" /f Makefile_agent
    - nmake CPU=AMD64 TLS=openssl TLSINCDIR="C:\OpenSSL-v111-Win64\include" TLSLIBDIR="C:\OpenSSL-v111-Win64\lib" PCREINCDIR="C:\projects\deps\libs\pcre\include" PCRELIBDIR="C:\projects\deps\libs\pcre\lib" /f Makefile_sender
    - nmake CPU=AMD64 TLS=openssl TLSINCDIR="C:\OpenSSL-v111-Win64\include" TLSLIBDIR="C:\OpenSSL-v111-Win64\lib" PCREINCDIR="C:\projects\deps\libs\pcre\include" PCRELIBDIR="C:\projects\deps\libs\pcre\lib" /f Makefile_get

notifications:
  - provider: Email
    to:
      - sleuthhound@programs74.ru
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
