sudo: required
dist: bionic

language: c

os:
  - linux

compiler:
  - gcc

before_install:
  - sudo wget https://repo.zabbix.com/zabbix/3.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.4-1%2Bbionic_all.deb
  - sudo dpkg -i zabbix-release_3.4-1+bionic_all.deb
  - sudo apt-get update -qq
  - sudo apt-get install -y autoconf automake wget unzip libxml2-dev libssl-dev libcurl4-openssl-dev libsnmp-dev libevent-dev libsqlite3-dev libpcre2-dev libssh2-1-dev libiksemel-dev libmariadbclient-dev-compat

script:
  - bash bootstrap.sh
  - ./configure --with-libpthread --with-libpcre --with-libcurl --with-libxml2 --with-net-snmp --with-openssl --enable-ipv6 --with-ssh2 --with-jabber --enable-server --enable-proxy --enable-agent --sysconfdir=/etc/zabbix --with-mysql
  - make
