sudo: required
dist: bionic

language: c

os:
  - linux

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y autoconf automake wget unzip gettext libxml2-dev libssl-dev libcurl4-openssl-dev libsnmp-dev libevent-dev libsqlite3-dev libpcre2-dev libssh2-1-dev libiksemel-dev libmariadbclient-dev-compat libopenipmi-dev unixodbc-dev

script:
  - chmod a+x create/bin/*.{sh,pl}
  - bash bootstrap.sh
  - ./configure --with-libpthread --with-libpcre --with-libcurl --with-libxml2 --with-net-snmp --with-openssl --enable-ipv6 --with-ssh2 --with-jabber --with-openipmi --with-unixodbc --enable-server --enable-proxy --enable-agent --enable-java --sysconfdir=/etc/zabbix --with-mysql
  - make
  - make dbschema
  - make gettext
